version: '3.8'

services:
  user-easydine:
    build:
      context: .
      dockerfile: Dockerfile
    image: user-easydine:latest
    container_name: user-easydine
    ports:
      - "3100:3100"
    restart: unless-stopped
    networks:
      - admin-easydine

networks:
  admin-easydine:
    name: admin-easydine
    external: true