version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: user-easydine_frontend:latest
    container_name: user-easydine
    ports:
      - "3100:3100"
    networks:
      - user-easydine
networks:
  user-easydine:
    name: user-easydine
    external: true