name: Deploy User-EasyDine Frontend to Ubuntu Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v4

      # Cài Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"

      # Build frontend
      - name: Build Frontend
        run: |
          npm install
          npm run build

      # Deploy qua SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            mkdir -p /home/aris/user-easydine
            cd /home/aris/user-easydine

            # Pull repository
            git pull origin main

            # Kiểm tra file cấu hình
            if [ ! -f nginx.conf ]; then
              echo "Error: nginx.conf not found!"
              exit 1
            fi

            # Kiểm tra và load nginx:alpine3.20
            if ! docker image inspect nginx:alpine3.20 >/dev/null 2>&1; then
              if [ -f /home/aris/nginx-alpine3.20.tar ]; then
                docker load -i /home/aris/nginx-alpine3.20.tar
              else
                docker pull nginx:alpine3.20
              fi
            fi

            # Tạo network user-easydine
            if ! docker network inspect user-easydine >/dev/null 2>&1; then
              docker network create user-easydine
            fi

            # Xóa và tạo thư mục dist
            rm -rf dist
            mkdir -p dist

      # Sao chép thư mục dist
      - name: Copy Build to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "./dist/*"
          target: "/home/aris/user-easydine/dist"

      # Chạy Docker Compose
      - name: Run Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/aris/user-easydine
            docker-compose down
            docker-compose build
            docker-compose up -d --force-recreate
            docker image prune -f