name: Deploy EasyDine Frontend to Ubuntu Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v4

      # Cài Node.js để build frontend
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.17.0"

      # Build frontend
      - name: Build Frontend
        env:
          CI: false
          REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
          REACT_APP_MINIO_API_URL: ${{ secrets.REACT_APP_MINIO_API_URL }}
        run: |
          npm install
          npm run build
          ls -la build  # Kiểm tra build output

      # Deploy qua SSH với password
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # Kiểm tra và load nginx:alpine3.20
            if ! docker image inspect nginx:alpine3.20 >/dev/null 2>&1; then
              if [ -f /home/aris/nginx-alpine3.20.tar ]; then
                docker load -i /home/aris/nginx-alpine3.20.tar
              else
                docker pull nginx:alpine3.20
              fi
            fi

            # Tạo network admin-easydine
            if ! docker network inspect admin-easydine >/dev/null 2>&1; then
              docker network create admin-easydine
            fi

            # Pull code và chuẩn bị thư mục
            cd /home/aris/admin-easydine
            git pull origin main
            rm -rf build
            mkdir -p build

      # Sao chép thư mục build
      - name: Copy Build to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "./build/*"
          target: "/home/aris/admin-easydine/build"

      # Chạy Docker Compose
      - name: Run Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/aris/admin-easydine
            docker-compose down
            docker-compose up -d --build --force-recreate
            docker image prune -f
            ls -la build

      # Kiểm tra sức khỏe
      - name: Check Frontend Health
        run: |
          sleep 10
          curl -f http://${{ secrets.SERVER_IP }}:3000 || exit 1
